"""add upload_download_domains

Revision ID: 0d7ca8e24cc3
Revises: 57eba0a293f2
Create Date: 2025-01-10 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d7ca8e24cc3"
down_revision = "57eba0a293f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hosts",
        sa.Column("upload_host", sa.String(1024), nullable=True),
    )
    op.add_column(
        "hosts",
        sa.Column("download_host", sa.String(1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "download_host")
    op.drop_column("hosts", "upload_host")
    # ### end Alembic commands ###
