"""add doh settings

Revision ID: 2b15b23dd3ec
Revises: 0d7ca8e24cc3
Create Date: 2025-01-10 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b15b23dd3ec"
down_revision = "0d7ca8e24cc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column("doh", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "doh")
    # ### end Alembic commands ###
